#######################
# Workflow Definitions
#######################

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - build-push:
          requires:
            - test
          filters:
            branches:
              only: master

  nightly:
    jobs:
      - test
    triggers:
      - schedule:
          cron: 0 0 * * *
          filters:
            branches:
              only: develop

#######################
# Job Definitions
#######################
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10.15.1-browsers
    working_directory: ~/ci-cd-101-workshop
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run test suite
          command: yarn test
      - persist_to_workspace:
          root: .
          paths:
            - Dockerfile
            - etc
            - css
            - img
            - index.html
            - js
            - mail
            - scss

  build-push:
    docker:
      - image: circleci/node:10.15.1-browsers
    working_directory: ~/ci-cd-101-workshop

    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build and tag the Docker image
          command: docker build -t $DOCKER_TAG -t ${DOCKER_TAG}:${CIRCLE_SHA1} .
      - run:
          name: Login to Dockerhub and push
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_TAG
            docker push ${DOCKER_TAG}:${CIRCLE_SHA1}

